http:
  routers:
    adguardhome:
      entryPoints:
        - websecure
      rule: Host("{{ env "ADGUARDHOME_DOMAIN" }}")
      tls:
        certResolver: ovh
      service: adguardhome
  
    adguardhome_no_domain:
      entryPoints:
        - adguardhome
      rule: HostRegexp(`.*`)
      tls:
        certResolver: ovh
      service: adguardhome

  services:
    adguardhome:
      loadBalancer:
        servers:
          - url: http://adguardhome
