http:
  routers:
    lockate:
      entryPoints:
        - websecure
      rule: Host("{{ env "LOCKATE_DOMAIN" }}")
      tls:
        certResolver: ovh
      service: lockate

    lockate-no-domain:
      entryPoints:
        - lockate
      rule: Host(`.*`)
      tls:
      service: lockate      

  services:
    lockate:
      loadBalancer:
        servers:
          - url: "http://lockate-api:3118"
